name: Build Backend using Shared Pipeline

on:
  push:
    branches: 
      - main

jobs:
  build-backend:
    uses: Muhammad-Rahim-2024/shared-pipelines/.github/workflows/build.yml@main


    with:
      project-name: test-backedn
      date: 7-3-2026
      # login to dockerhub using input/variables
      dockerhub-username-input: muhammadrahimharoon
      

    # login to dockerhub using secrets
    secrets:
      dockerhub-username: ${{ secrets.DOCKERHUB_USER }}
      dockerhub-password: ${{ secrets.DOCKERHUB_PASS }}



  
